### ISSUE TITLE
Admin Panels

### ISSUE THREAD

**Issue by lrnzdc3696** [YameTechs/website#7]
This is where we can control what happens on accounts or something

**Comment by lrnzdc3696** [comment]
# Todo

- [x] rename /admin to /db then add it to /admin/db
- [x] admin overview
- [ ] route to "post, edit, & delete" services
- [x] secure /admin via [this](https://stackoverflow.com/questions/34164464/flask-decorate-every-route-at-once)

**Comment by lrnzdc3696** [comment]
#40 done
